config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products

  authenticated :user do
    root 'home#index'
  end

  unauthenticated :user do
    root 'home#unregistered'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_params, if: :devise_controller?

  private

  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :last_name, :bio, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def unregistered
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.all
  end

  def show
   
  end

  def new 
    @product = Product.new
  end

  def edit
    
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def destroy
    @product.destroy

    redirect_to @products_oath
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:code, :description, :unity, :stock, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/main" %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/partials/_main.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-end">
  <a><%= link_to "Tecnyfarma", root_path, class: "navbar-brand" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav float-left">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <a><%= link_to "Crear Producto", new_product_path, class: "nav-link" %><span class="sr-only"></span></a>
        </li>

        <li class="nav-item">
          <a><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-link" %></a>
        </li>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form>
      <% else %>
        <li class="nav-item active">
          <a><%= link_to "Registrate", new_user_registration_path, class: "nav-link" %></a>
        </li>

        <li class="nav-item">
          <a><%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %></a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">

    <h2><%= name %> Producto</h2>
    <br><br><br>


    <div class="form-group">
      <%= form.label :code, "Código:" %>
      <%= form.number_field :code, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description, "Descripción del producto:" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :unity, "Unidad de medida:" %>
      <%= form.text_field :unity, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :stock, "Cantidad disponible:" %>
      <%= form.number_field :stock, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :date, "Fecha de actualización:" %>
      <%= form.date_field :date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit "Guardar", class: "btn btn-primary" %>
    </div>

  </div>
<% end %>

app/views/products/edit.html.erb
<%= render "form", name: "Editar" %>

app/views/products/index.html.erb
<div class="container">
  <h2>Productos</h2>
  <br><br>
  
  <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Código</th>
      <th scope="col">Descripción del producto</th>
      <th scope="col">Unidad de medida</th>
      <th scope="col">Cantidad disponible</th>
      <th scope="col">Fecha actualizada</th>
      <th scope="col">Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <th scope="row">#</th>
        <td><%= product.code %></td>
        <td><%= product.description %></td>
        <td><%= product.unity %></td>
        <td><%= product.stock %></td>
        <td><%= product.date %></td>
        <td><%= link_to "Ver más..", product_path(product), class: "btn btn-primary" %></td>
        <% if user_signed_in? %>
          <td><%= link_to "Editar", edit_product_path(product), class: "btn btn-success" %></td>
          <td><%= link_to "Eliminar", product_path(product), class: "btn btn-danger", method: :delete, data: { confirm: "Seguro que decea eliminarlo? " } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/products/new.html.erb
<%= render "form", name: "Crear" %>

app/views/products/show.html.erb
<p>
  <strong>Código:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Unidad de medida:</strong>
  <%= @product.unity %>
</p>

<p>
  <strong>Cantidad disponible:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Fecha de actualización:</strong>
  <%= @product.date %>
</p>